# Generated by Django 3.0.4 on 2020-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=100)),
                ('versionCode', models.CharField(max_length=10)),
                ('branchName', models.CharField(max_length=100)),
                ('downloadUrl', models.CharField(max_length=300)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
